CREATE DATABASE IF NOT EXISTS cops_sql;

-- MySQL Script generated by MySQL Workbench
-- Tue Nov 12 23:31:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cops_sql
-- -----------------------------------------------------
USE `cops_sql`;

-- -----------------------------------------------------
-- Table `cops_sql`.`policias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cops_sql`.`policias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NULL,
  `rango` ENUM('CADETE', 'OFICIAL') NULL DEFAULT 'CADETE',
  `id_policia` VARCHAR(225) NOT NULL,
  `contrasena` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SELECT UUID() AS UUID_VALUE;

CREATE UNIQUE INDEX `id-policia_UNIQUE` ON `cops_sql`.`policias` (`id-policia` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `cops_sql`.`descripcion_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cops_sql`.`descripcion_fisica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rasgos_faciales` VARCHAR(255) NOT NULL,
  `color _cabello` VARCHAR(45) NOT NULL,
  `estatura` VARCHAR(45) NOT NULL,
  `complexion` VARCHAR(45) NOT NULL,
  `color_ojos` VARCHAR(45) NOT NULL,
  `lentes` TINYINT NULL DEFAULT 0,
  `tatuajes` TINYINT NULL DEFAULT 0,
  `descripcion_fisicacol` VARCHAR(45) NOT NULL,
  `tipo_cabello` VARCHAR(45) NOT NULL,
  `descripcion_fisicacol1` VARCHAR(45) NOT NULL,
  `descripcion_fisicacol2` VARCHAR(45) NOT NULL,
  `descripcion_fisicacol3` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cops_sql`.`ciudadanos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cops_sql`.`ciudadanos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `cedula` INT NOT NULL,
  `sexo` ENUM('M', 'F') NOT NULL,
  `estado_civil` ENUM('SOLTERO', 'CASADO', 'DIVORCIADO', 'VIUDO') NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `descripcion_fisica_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ciudadanos_descripcion_fisica1`
    FOREIGN KEY (`descripcion_fisica_id`)
    REFERENCES `cops_sql`.`descripcion_fisica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE UNIQUE INDEX `cedula_UNIQUE` ON `cops_sql`.`ciudadanos` (`cedula` ASC) VISIBLE;

CREATE INDEX `fk_ciudadanos_descripcion_fisica1_idx` ON `cops_sql`.`ciudadanos` (`descripcion_fisica_id` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `cops_sql`.`contactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cops_sql`.`contactos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_ciudadano` INT NOT NULL,
  `tipo` ENUM('TELEFONO', 'CORREO') NOT NULL,
  `dato` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_ciudadano`
    FOREIGN KEY (`id`)
    REFERENCES `cops_sql`.`ciudadanos` (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cops_sql`.`direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cops_sql`.`direcciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `pais` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(100) NOT NULL,
  `ciudad` VARCHAR(100) NOT NULL,
  `codigo_postal` INT NOT NULL,
  `ciudadanos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_direcciones_ciudadanos1`
    FOREIGN KEY (`ciudadanos_id`)
    REFERENCES `cops_sql`.`ciudadanos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_direcciones_ciudadanos1_idx` ON `cops_sql`.`direcciones` (`ciudadanos_id` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `cops_sql`.`delitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cops_sql`.`delitos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cops_sql`.`reportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cops_sql`.`reportes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `id_policia` INT NOT NULL,
  `descripcion` TEXT NOT NULL,
  `estatus` ENUM('IMPUTADO', 'CULPABLE', 'INOCENTE') NULL,
  `ciudadanos_id` INT NOT NULL,
  `direcciones_id1` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_policias`
    FOREIGN KEY (`id`)
    REFERENCES `cops_sql`.`policias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reportes_ciudadanos1`
    FOREIGN KEY (`ciudadanos_id`)
    REFERENCES `cops_sql`.`ciudadanos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reportes_direcciones1`
    FOREIGN KEY (`direcciones_id1`)
    REFERENCES `cops_sql`.`direcciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_reportes_ciudadanos1_idx` ON `cops_sql`.`reportes` (`ciudadanos_id` ASC) VISIBLE;

CREATE INDEX `fk_reportes_direcciones1_idx` ON `cops_sql`.`reportes` (`direcciones_id1` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `cops_sql`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cops_sql`.`cargos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NOT NULL,
  `fecha` DATE NOT NULL,
  `delitos_id` INT NOT NULL,
  `reportes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `delitos_id`, `reportes_id`),
  CONSTRAINT `fk_cargos_delitos1`
    FOREIGN KEY (`delitos_id`)
    REFERENCES `cops_sql`.`delitos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cargos_reportes1`
    FOREIGN KEY (`reportes_id`)
    REFERENCES `cops_sql`.`reportes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cargos_delitos1_idx` ON `cops_sql`.`cargos` (`delitos_id` ASC) VISIBLE;

CREATE INDEX `fk_cargos_reportes1_idx` ON `cops_sql`.`cargos` (`reportes_id` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `cops_sql`.`Condena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cops_sql`.`Condena` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `sentencia` VARCHAR(255) NULL,
  `tiempo_duracion` VARCHAR(255) NULL,
  `condiciones` TEXT NULL,
  `reportes_id` INT NOT NULL,
  `reportes_cargos_cometidos_cargos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `reportes_id`, `reportes_cargos_cometidos_cargos_id`),
  CONSTRAINT `fk_Condena_reportes1`
    FOREIGN KEY (`reportes_id`)
    REFERENCES `cops_sql`.`reportes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Condena_reportes1_idx` ON `cops_sql`.`Condena` (`reportes_id` ASC, `reportes_cargos_cometidos_cargos_id` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `cops_sql`.`evidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cops_sql`.`evidencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NULL,
  `fecha_hora` DATETIME NULL,
  `tipo` TEXT NULL,
  `estado` ENUM('REVISION', 'REVISADA', 'ACEPTADA', 'RECHAZADA') NULL,
  `reportes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `reportes_id`),
  CONSTRAINT `fk_evidencia_reportes1`
    FOREIGN KEY (`reportes_id`)
    REFERENCES `cops_sql`.`reportes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_evidencia_reportes1_idx` ON `cops_sql`.`evidencia` (`reportes_id` ASC) VISIBLE;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;